# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0broute.proto\"\x1b\n\rLookupRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x10\n\x0eLookupResponse\"\x1b\n\x0bTestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cTestResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x0b\x46indRequest\x12\n\n\x02id\x18\x01 \x01(\t\"I\n\x10\x46indNodeResponse\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x10\n\x08udp_port\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\t\"L\n\x11\x46indValueResponse\x12(\n\rfind_node_res\x18\x01 \x01(\x0b\x32\x11.FindNodeResponse\x12\r\n\x05value\x18\x02 \x01(\t\"*\n\x0cStoreRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\"\n\rStoreResponse\x12\x11\n\tis_stored\x18\x01 \x01(\x08\"\r\n\x0bPingRequest\"\x0e\n\x0cPingResponse2\x95\x02\n\x06Router\x12+\n\nTestRouter\x12\x0c.TestRequest\x1a\r.TestResponse\"\x00\x12/\n\x08\x46indNode\x12\x0c.FindRequest\x1a\x11.FindNodeResponse\"\x00\x30\x01\x12/\n\tFindValue\x12\x0c.FindRequest\x1a\x12.FindValueResponse\"\x00\x12(\n\x05Store\x12\r.StoreRequest\x1a\x0e.StoreResponse\"\x00\x12%\n\x04Ping\x12\x0c.PingRequest\x1a\r.PingResponse\"\x00\x12+\n\x06Lookup\x12\x0e.LookupRequest\x1a\x0f.LookupResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOOKUPREQUEST']._serialized_start=15
  _globals['_LOOKUPREQUEST']._serialized_end=42
  _globals['_LOOKUPRESPONSE']._serialized_start=44
  _globals['_LOOKUPRESPONSE']._serialized_end=60
  _globals['_TESTREQUEST']._serialized_start=62
  _globals['_TESTREQUEST']._serialized_end=89
  _globals['_TESTRESPONSE']._serialized_start=91
  _globals['_TESTRESPONSE']._serialized_end=122
  _globals['_FINDREQUEST']._serialized_start=124
  _globals['_FINDREQUEST']._serialized_end=149
  _globals['_FINDNODERESPONSE']._serialized_start=151
  _globals['_FINDNODERESPONSE']._serialized_end=224
  _globals['_FINDVALUERESPONSE']._serialized_start=226
  _globals['_FINDVALUERESPONSE']._serialized_end=302
  _globals['_STOREREQUEST']._serialized_start=304
  _globals['_STOREREQUEST']._serialized_end=346
  _globals['_STORERESPONSE']._serialized_start=348
  _globals['_STORERESPONSE']._serialized_end=382
  _globals['_PINGREQUEST']._serialized_start=384
  _globals['_PINGREQUEST']._serialized_end=397
  _globals['_PINGRESPONSE']._serialized_start=399
  _globals['_PINGRESPONSE']._serialized_end=413
  _globals['_ROUTER']._serialized_start=416
  _globals['_ROUTER']._serialized_end=693
# @@protoc_insertion_point(module_scope)
